# Config file for automatic testing at travis-ci.org
language: python

cache: pip

services:
  - xvfb  # used for GUI testing

matrix:
    include:
      - python: 3.6
        env: TEST_TYPE="pre-commit"
      - python: 3.6
        env: TEST_TYPE="pytest" PYPI_DEPLOY=true
      - python: 3.7
        env: TEST_TYPE="pytest"
      - python: 3.6
        env: TEST_TYPE="docs" READTHEDOCS="True"

install:
  - pip install --upgrade pip wheel setuptools
  - |
      if [[ "$TEST_TYPE" == "pre-commit" ]]; then
        pip install -e .[code_style]
      fi
  - |
      if [[ "$TEST_TYPE" == "pytest" ]]; then
        pip install -e .[threejs,testing]
        pip install coveralls
      fi
  - |
      if [[ "$TEST_TYPE" == "docs" ]]; then
        pip install -e .[threejs,svgconcat,docs]
        url="https://github.com/jgm/pandoc/releases/tag/2.6"
        path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
        downloadUrl="https://github.com$path"
        file=${path##*/}
        wget $downloadUrl && sudo dpkg -i $file
      fi

script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      # pytest -v --nb-test-files --log-cli-level=info --cov=pytest_notebook --cov-report=
      pytest -v --cov=ase_notebook --cov-report=
  fi
- |
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
    pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  fi
- |
  if [[ "$TEST_TYPE" == "docs" ]]; then
    cd docs
    make
  fi

after_success:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      coveralls
  fi

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: cjsewell
    password:
      secure: K4w/19Bp0WqT7aNHU0IaEZRnNvLPDZoPLeYglmXnAdibimMBds9KsqzmdxpPc9OkUbEhA0fKs61tRqbWsujB1j59oMqM9ZvCTl8feL+q361zPkOvWn/owMFbpJmORln2uQzkKdpFBocu+FKCcoAsvx3V8wamcI0jy64yq4g6ABOhyWgNzn1rEgV9S5Hx1ykq+uBem9UucsrbCUnsql6ElM1Btf9IFu9dA/CS1u+LlLzeIpaheFG2oopxptFUUu8NB2iJq8vxv9j+2WzXaT0f9oEy2Z6K2gLYA3/sj5YtJX/AsR/qWWFIQArZvA2ytwRe8PM2dDbxV8Sz04EhRQI8iQu6FCgpA1ezXC5n66WZPT73Yu+EshUiXqfZxghjCKsYFscJ9vg/kld2J7leCeIWzwksKYyeD5SgQ8vAuS5YBkl0XQtAZ/er1qcv7fRQMVSWw/cLJe9LxNjOmTkd9kebZgVpvr3/sVcewhgkOd8vBNwXugqBZ38eedSrygw3kIg/RY3FqlSOiyxjWwlpEJ7Zi78Fjt47CWRHPIg6kpKHR1p7yfdS0L6NQdc2VzhnaAmkVNcsRJ3ByadpoT9PlaYg+J/AcB65twMTJ+MsG6Vb92dDaEgx9bBabmnwyd0yAebu1yO0507AYHHj/GOUkskRCuvSYmd6oWY58otiAwsNpnQ=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
